#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'
picom &
~/.fehbg &
setxkbmap -v workman-p
xset r 66
sxhkd &
pkill xmobar; xmobar ~/.config/xmobar/xmobar.config &

hc pad 0 22

# Uncomment the following lines to use xmobar as the panel
# Remember to comment out the last 8 lines of this config, so that
# polybar will no longer launch on startup.
# $HOME/.config/herbstluftwm/xmobar

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4                            # Use the super key as the main modifier
myTerm=kitty                        # Set my preferred terminal

hc keybind $Mod-Shift-q quit
hc keybind $Mod-q reload
hc keybind $Mod-x chain , close , remove
hc keybind $Mod-Shift-x close
hc keybind $Mod-Return chain , split explode , cycle_all +1 , spawn $myTerm
hc keybind $Mod-Shift-Return spawn $myTerm

# menus
hc keybind $Mod-o spawn rofi -show drun
hc keybind $Mod-Shift-space spawn dkeys

# misc
hc keybind $Mod-Shift-s spawn scrot '/home/jacob/images/scrots/%Y-%m-%d-%H:%M:%S_scrot.png'

# My applications (Super+Alt+Key)
# hc keybind $Mod-Mod1-l spawn $myTerm -e lynx -cfg=~/.lynx.cfg -lss=~/.lynx.lss http://www.distrowatch.com
# hc keybind $Mod-Mod1-n spawn $myTerm -e newsboat
# hc keybind $Mod-Mod1-e spawn $myTerm -e neomutt

# focusing clients
hc keybind $Mod-h             focus left
hc keybind $Mod-j             focus down
hc keybind $Mod-k             focus up
hc keybind $Mod-l             focus right
                              
# moving clients              
hc keybind $Mod-Shift-h       shift left
hc keybind $Mod-Shift-j       shift down
hc keybind $Mod-Shift-k       shift up
hc keybind $Mod-Shift-l       shift right

# splitting frames
hc keybind $Mod-Shift-Down    split  bottom  0.5
hc keybind $Mod-Shift-Right   split  right   0.5
hc keybind $Mod-e             split  explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h     resize left +$resizestep
hc keybind $Mod-Control-j     resize down +$resizestep
hc keybind $Mod-Control-k     resize up +$resizestep
hc keybind $Mod-Control-l     resize right +$resizestep

# tags
tag_names=("dev" "www" "sys" "doc" "vbox" "chat" "mus" "vid" "gfx")
tag_keys=(exclam at numbersign dollar percent caret ampersand asterisk parenleft)

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-z remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-space fullscreen toggle
hc keybind $Mod-Shift-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
# hc keybind $Mod-space                                                           \
#             or , and . compare tags.focus.curframe_wcount = 2                   \
#                      . cycle_layout +1 vertical horizontal max vertical grid    \
#                , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Shift-Button1 resize

# focus
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_padding 0
hc set focus_follows_mouse 1

hc attr theme.active.color '#ebcb8b'
hc attr theme.normal.color '#2e3440'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 1

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole|.+tty)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

panel=~/.config/herbstluftwm/panel.sh
"$panel" 0 &
